export default {
    fetching: 'fetching',
    fetched: 'fetched',
    error: 'error',
    con_fetching: 'con_fetching',
    con_fetched: 'con_fetched',
    con_error: 'con_error',
    reg_fetching: "reg_fetching",
    reg_fetched: 'reg_fetched',
    reg_error: 'reg_error',
    update_fetching: "update_fetching",
    update_fetched: "update_fetched",
    update_error: "update_error",
    verified_fetching: "verified_fetching",
    verified_fetched: "verified_fetched",
    verified_error: "verified_error",
    withdraw_fetching: "withdraw_fetching",
    withdraw_fetched: "withdraw_fetched",
    withdraw_error: "withdraw_error",
    address_fetching: "address_fetching",
    address_fetched: "address_fetched",
    address_error: "address_error",

};
